use std::io::Write;
use tempfile::NamedTempFile;

pub fn create_fastq_file(content: &str) -> NamedTempFile {
    let mut file = NamedTempFile::new().expect("failed to create temp file");
    write!(file, "{}", content).expect("failed to write to temp file");
    file
}

pub fn build_fq_data() -> (NamedTempFile, NamedTempFile) {
    let fq1 = create_fastq_file(
        "@HWI-ST765:123:D0TEDACXX:5:1101:2872:2088/1\n\
         TTGTCTTCCAGATAATTCCGCTATGTTCAACAAATATGTTAGATTCAAGTTTTTCTTGATAAACCTATTTAAAACCATGAAACTGATTCAATCGATTCAAT\n\
         +\n\
         CCCFFFFFHHHHGJJJJJJIJJJJJJJJJJJJJJJJIIIIJJJIJJIJJHIJJJJJIJIJJJIJJJJJJJJJIJJIJJHHHHHHFFFFFFEEEDEDDDDED\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:6511:2225/1\n\
         GGGGTTTGAATTGGAATTGAACAAACTCGTGGGACCCCTAGACTGACCGGCTATATACTCAACCTGCTCTAAAGTAAGTGTGGGACACTCGAGCGTGTCGT\n\
         +\n\
         @BCFDFFFHHHHHJJJJJJJJIJJJJIJJGIJJIIJJJEIJJJJIJJJJJJIJHHHHHHHFFFFFAEEEEDDDCDCCDCCEDDDDDDDDDDBBDDBDBDB<\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:12346:2094/1\n\
         CGTTCGTTAATTTAGTTAATTTAATTTAATTGCAAATTTTGGATTTTTAGAAACTCTCCCTCTCAAACATAAAAAATAGTTAGTGTCGCATCAGTGTCAGT\n\
         +\n\
         @C@FFFFFHFHHHHGHHIJJJJIIJJJIJGGIGHIJHIJJJJIIJJJJIGIIIJEIJJIIIGHIIGIJJJIIIIIHEFFBCFFC>AECDDDDDDCCCDDDD\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:16473:2185/1\n\
         GCGTGTTGGGCTGACGCCAACCAAATGACGGTGGTTAGGATGGCGGTCAGGTCCTCGACGTTAGCCAATGTGGGCCACCATGTCTCATTGCGAAGTTCAGC\n\
         +\n\
         @CCDDFDFFHGHFJIGGHGEHGGHGGIEGHI6BF?BFHECBHHGGHDEFCE>;>@CB@BBBBDBDC@CDCDD@B22<?@BD>:C:AA>CCDDB@@8@DCCC\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:11717:2411/1\n\
         ACACAATGTGCAAGCCAATTAGAAGCCAACTGGACAGCACTGAAGGCTTGGAAAAGTGGCTATAAAAGTTACATAAATAAAGAAGATGTTTTATTTCAAAT\n\
         +\n\
         @@@DD;DA=C>FB?GFFGECHBHIEFBGBCFGF<BFEI;BGFF4?>BGEIFCCF;;BCC;FFFEE@)=7A;==CA:7?BBD>@CCCCB;;@BBBBDEA>A;\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:16191:2473/1\n\
         TTTTATCATCTTCCTCTTAGTTTGTTCTCTCTATTTATTCGTGTCCCTTTTTTTTATTTATTGTATTAGCAAACTAAATATCTATATCTAAAATATGGTTA\n\
         +\n\
         CCCFFFFFHHHHHJJJJJJJHIJJIJIJIGGJJJJJIJJJJGHHIIJJJJJJIJJGIJJJJJIIJHHHBEEEFFFFFEEEFEDEEFEEFEDCDEDEEDACC\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:16583:2310/1\n\
         CCATCCCCTCTCATCTATCCAAAGCCAACCGTATAATCATGGAACTTGAGAAACAACGCATTCGAGCAAAATATCTCAACAAGAAGTCTATGTTTATGTTT\n\
         +\n\
         CCCFFFFFHHHHHIGIIIJJJJJJJJJJJHIGHGJIJIJJIJIJIIGIIJGJGHGIEIJGIHGGHFEFFFEEEFFDEDDDDBDDDD>ACADD@DEDDDDED\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:17034:2404/1\n\
         CATTTGCGGTACTTCACACTAGCATGATGATGAAGGGTGCAATCGTTGCACAAGGGTGCAGTTCCGTTGTATGGCTTTCTAGCAGGGGGTTGAGTTGGTTG\n\
         +\n\
         @CCFFFFFHHHHHIJJJJJJJJJJJJJJJJJJJJJJJ?FHIJIIJIIIJIJJJJJJ@FHIJEIHHHAHFFFFFEDEEDDDEDDDDDDDD9@DCD@DCD@BB\n"
    );

    let fq2 = create_fastq_file(
        "@HWI-ST765:123:D0TEDACXX:5:1101:2872:2088/2\n\
         ATTGTGTTATAAAGTTTATTTCTATTTCCGTTGCAACTTAAATCTGATTTACATTCATTTTACTTAAACAAACACAATCAAAAGAAACTCAGATCCTACAA\n\
         +\n\
         CCCFDFFFHHHHHIHIJJJJJJJJJJJJJJJJJJJJJJJIJIIIJJJJJJJJJJJJIJIJJJJJJJIJJJJJJJJJGIJJHHHHHFBEDFDDEEDDDDDDD\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:6511:2225/2\n\
         AAAGAAGACGGTGACTGAGTGCAATGATTTGTTCGAGAGTTTTGCACATTCTGATATGGACTACAGCACTGCCAGCAGGACTTCCATTCCTGTTACTACCA\n\
         +\n\
         CCCFFFFFHHHDHIIIGIJHGIJJJJJJJJIIJJIGIIJGIIJJJJJJJJIJIIIJJIJIJJIJJJIJJJIHHHHFFFFDDECEEDDEEFDDDDDDDEDD>\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:12346:2094/2\n\
         TCAATTAAGTCCAAATAAAGTAATCAATGCAATTGCCAAAGAGTCCGCGGCAACGGCGCCAAAAAACTTGATGTGCTAAAAGTAGTTTAATAAAACAACTA\n\
         +\n\
         @CCFFFEFHFFFFIIJIIJIIFHIJJGGHIJJIJIJJIJJIIIFHIJIJIIIGJGHGDDDDDDDDDDDDDDDDDCDDDDDDDDDDCDDEDDEDCCCBDDDD\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:16473:2185/2\n\
         GTTGATTATGTTCTCATGCATACAGGGGTATGGCGATCCCGGACCCAAGTCAGCGACATGGACTCAAGCTTTTAATCGAAGACTACCCGTACGCTTCTGAC\n\
         +\n\
         @@BFFFFDHHHHDHIJHJIJJJJGHIJIFDCHJCHIGIJJIJJJIIIIIHCEIGHHFFFEECEEDDD>A>ACDDDDDBBABBDDDCDBDDBBDDB@BCDCC\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:16583:2310/2\n\
         TCCCTTTTATTTATTTTGTTTTTATGAACTTTTGTGATATTGTTGATCACTAGCAGTGGTGTAGCATTGGTGCTATTTGGTACGGTTTACCCTGCACGCGG\n\
         +\n\
         CCCFFFFFGHHHHIJJJJHIJJJGJJJJIIJJJJFEHIIIIIIIJJJJJJIIJJIIGHJFDDFGGHCHIGFFHIJJJJJIEHGHFEFDECCCE(;ACBDDD\n\
         @HWI-ST765:123:D0TEDACXX:5:1101:17034:2404/2\n\
         AAAGGTGACAAGAAACCAATCGAAGAATCAAAACCTAAGGATAAACAGACTGAATCCTCCAAGAAGTCAAAGAAGCGGAAGGCTTCTCAGAACTTCACCGT\n\
         +\n\
         BCCFFDDFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJJJJIJJJJJJJJJIJJJJJJJJGIJJJJJHIHGHHHHFFFDCDDDDDDDDDEDDCDDDDDDDDB\n"
    );

    (fq1, fq2)
}
